@startuml

actor Buchende
participant "IDP (Identitätsprovider)" as IDP
participant "Termin Requestor (z.B. Patientenportal, Providerportal etc.)" as TR
participant "Termin Repository" as TRP
participant "BasisServer (ggf. 'Patientenführendes Sytem' etc.)" as BS

Buchende -> IDP: Registrierung mit Name und E-Mail \n (ggf. Geburtsdatum, Adresse, Versicherung, gID, KVNR, HBA etc.) 
note right of IDP: ggf. IDP nur für Identitätsprüfung auf E-Mail-Ebene, \n fortgeschritten wäre gID mit KVNR, ggf. externer Arzt mit HBA etc)
IDP --> TR: Validiere Identität Buchende Person (validierte Identität, z.B. KVNR)
note right of TR: Identität verifiziert

TR -> TRP: Anfrage verfügbare Termine für Fachbereich
TRP -> BS: Lookup Patient (ggf. basierend auf KVNR)
BS -> BS: Match Patient
note right of BS: ggf. mit vorgeschaltetem MPI
BS -> TRP: Patientendaten zurückliefern
TRP -> TR: Rückgabe verfügbarer Termine
TR -> Buchende: Visualisierung der verfügbaren Termine

Buchende -> TR: Auswahl eines Termins
TR -> TRP: Erstellen des Termins (vorläufig)
note right of TRP: Termin ist angelegt, Patient verifiziert
TR -> BS: GET Patientendaten zur Verknüpfung
BS -> TR: Patientendaten zurückgeben
TR -> TRP: Verknüpfung des Termins mit Patientendaten

TRP -> TR: Buchungsbestätigung
TR -> Buchende: Bestätigung per E-Mail/SMS

@enduml
