@startuml dummy
' package Dummy{
' entity Entität01 {
'    optionales Attribut
'    **optionales fettes Attribut**
'    * **vorgeschriebens fettes Attribut**
' }
' 
' entity Entität01 {
'    optionales Attribut : text
'    **optionales fettes Attribut** nummer <<auto>>
'    * **vorgeschriebens fettes Attribut**
' }
' Entität01 }|..|| Entität02
' Entität03 }o..o| Entität04
' Entität05 ||--o{ Entität06
' Entität07 |o--|| Entität08
' }
@enduml


' TODO:
' Vervollständigen im Sinne  von: https://github.com/gematik/spec-ISiK-Medikation/blob/rc/main-stufe-4/Material/docs/Medikation%20Abgleich%20bestehende%20Spezifikationen.xlsx

@startuml infomodell
'verhindere Probleme mit gewinkelten Krähenfüßen
'skinparam linetype ortho

'together enhancement
set separator none



'ISiK_Medikation.ISiKMedikationsListe::subject --> ISiK_Basis.ISiKPatient
'ISiK_Medikation.ISiKMedikationTransaction --> R4_Core.Bundle
'ISiK_Medikation.ISiKMedikationTransactionResponse --|> R4_Core.Bundle


together ISiK_Terminplanung {

   class ISiKKalender <Schedule><<(P,#8DA5C4)>>{
   extension : **ScheduleName**
   |_ (All Slices)
      |_ <s> extension </s>
      |_ KalenderName : **Extension**
   active
   serviceType
   specialty
   |_ Fachrichtung : **IHEXDSauthorSpeciality**
   actor : Reference ( **Patient** | **Practitioner** | PractitionerRole | \n\t**RelatedPerson** | Device | HealthcareService | Location)
   |_ identifier
   |_ display
   |_ Akteur : Reference (**Practitioner** | HealthcareService)
      |_ reference
   }

   class ISiKMedizinischeBehandlungseinheit <HealthcareService><<(P,#8DA5C4)>>{
   active
   type
   specialty
   |_ Fachrichtung : **IHEXDSauthorSpeciality**
   name
   }

   class ISiKNachricht <Communication><<(P,#8DA5C4)>>{
   inResponseTo : Reference (Communication)
   status
   subject : Reference ( **Patient** )
   sent
   recipient : Reference ( Device | Organization | **Patient** | **Practitioner** | \n\tPractitionerRole | **RelatedPerson** | Group | CareTeam | HealthcareService)
   |_ identifier
   |_ display
   |_ ISiKRecipient : Reference ( **Practitioner** | HealthcareService)
      |_ reference
   sender : Reference ( Device | Organization | **Patient** | **Practitioner** | \n\tPractitionerRole | **RelatedPerson** | HealthcareService)
   |_ reference
   payload : BackboneElement
   |_ content[x]
      |_ contentString
      |_ contentAttachment
         |_ contentType
         |_ <s>data</s>
         |_ url
         |_ creation
   }

   class ISiKTermin <Appointment><<(P,#8DA5C4)>>{

   }

   class ISiKTerminblock <Slot><<(P,#8DA5C4)>>{

   }

   class ISiKTerminKontaktMitGesundheitseinrichtung <Encounter><<(P,#8DA5C4)>>{

   }

   'Extensions

   class ScheduleName <<(E,#7A8495)>>{
   Dokumentation auf Simplifier 
   [[https://simplifier.net/isik-terminplanung-v4/schedulename ScheduleName]]
   }

   class AppointmentReplaces <<(E,#7A8495)>>{
   Dokumentation auf Simplifier 
   [[https://simplifier.net/isik-terminplanung-v4/appointmentreplaces AppointmentReplaces]]
   }

   class ISiKNachrichtExtension <<(E,#7A8495)>>{
   Dokumentation auf Simplifier 
   [[https://simplifier.net/isik-terminplanung-v4/isiknachrichtextension ISiK Nachricht Extension]]
   }

   class ISiKTerminPriorityExtension <<(E,#7A8495)>>{
   Dokumentation auf Simplifier 
   [[https://simplifier.net/isik-terminplanung-v4/isikterminpriorityextension ISiKTermin Priority Extension]]
   ---
   value[x] : **ISiKTerminPriority (required)**
   |_ valueCodeableConcept
   }
}

together MII_Kerndatensatz {
   
}

together R4_Core {
   
}

together ISiK_Basis {
   class Basismodul_Stufe_3 <<(M,#FFDC36)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/~introduction ISiK Basis Stufe 3]]
   }
   class ISiKPatient <Patient><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikpatient ISiK Patient]]
   }
   class ISiKKontaktGesundheitseinrichtung <Encounter><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikkontaktgesundheitseinrichtung ISiK Kontakt Gesundheitseinrichtung]]
   }
   class ISiKPractitioner <Practitioner><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikpersonimgesundheitsberuf ISiK Person im Gesundheitsberuf]]
   }
   class ISiKDiagnose <Condition><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikdiagnose ISiK Diagnose]]
   }
   class ISiKProzedur <Procedure><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikprozedur ISiK Prozedur]]
   }
   class ISiKAngehoeriger <RelatedPerson><<(P,#8DA5C4)>>{
      Dokumentation auf Simplifier 
      [[https://simplifier.net/isik-basis-v4/isikangehoeriger ISiK Angehoeriger]]
   }  
}

'Realtions

'diamonds
together {
<> MultiRef_PracPatRel
MultiRef_PracPatRel -- ISiKPractitioner
MultiRef_PracPatRel -- ISiKPatient
MultiRef_PracPatRel -- ISiKAngehoeriger
<> MultiRef_KDLXDS
MultiRef_KDLXDS -- vsKDL
MultiRef_KDLXDS -- IHEXDStypeCode
}

'Relations
ISiKDokumentenSuchergebnisse::DocumentReference -down- "  1..1  "   ISiKDokumentenMetadaten 


ISiKDokumentenMetadaten::type -- "  1..1  " MultiRef_KDLXDS
ISiKDokumentenMetadaten::category -- "  0..1  " IHEXDSclassCode

ISiKDokumentenMetadaten::subject --> "  1..1  " ISiKPatient
ISiKDokumentenMetadaten::author <--> "  0..1  " MultiRef_PracPatRel
ISiKDokumentenMetadaten::securityLabel -up- "  1..*  "ISiKConfidentialityCodes  
ISiKDokumentenMetadaten::content -- "  1..1  " IHEXDSformatCodeDE
ISiKDokumentenMetadaten::encounter -- "  0..1  " ISiKKontaktGesundheitseinrichtung
ISiKDokumentenMetadaten::context -- "  1..1  " IHEXDSeventCodeList
ISiKDokumentenMetadaten::context -- "  1..1  " IHEXDShealthcareFacilityTypeCode
ISiKDokumentenMetadaten::context -- "  1..1  " IHEXDSpracticeSettingCode


'together dummy {
'   class Foo {
'   + field1
'   + field2
'   }
'   class Bar {
'   + field3
'   + field4
'   }
'   Foo::field1 --> Bar::field3 : foo
'   Foo::field2 --> Bar::field4 : bar
'}
@enduml