
@startuml searchtypes_interaction
left to right direction
'skinparam packageStyle cloud
skinparam linetype ortho


folder CSt_MedInfo as "Systeme mit dem Charakter der \n Medikationsinformation" {
    component _MedInfo [
        **ISiK MedikationsInformation**
        ====
        Suche anhand von
        * ** :** medication
        * ** :** patient
        * ** :** context
    ]
    
    component CStAll_MedikationsListe [
        **ISiK MedikationsListe**
        ====
        Suche anhand von
        * ** : ** medication
        * ** : ** patient
        * ** : ** context
    ]
    'component "ISiK MedikationsListe"
    component "ISiK Medikament"
    component "ISiK Patient"
    component "ISiK Kontakt Gesundheitseinrichtung"
    component "ISiK Person im Gesundheitsberuf"

}

folder CSt_MedAll as "Alle Systeme mit MedikationsCharakter" {
    component CStAll_Medikament [
        **ISiK Medikament**
        ====
        Suche anhand von
        * ** : ** ingredient
    ]
    component CStAll_Patient [
        **ISiK Patient**
        ====
        Finde alle zugehörigen
        * Encounter ** via ** patient
        * Encounter ** via ** subject
    ]
    component CStAll_KontaktGesundheitseinrichtung [
        **ISiK Kontakt Gesundheitseinrichtung**
        ====
        Suche anhand von
        * ** : ** patient
        * ** : ** subject
        * ** : ** part-of
        Finde alle zugehörigen
        * Encounter ** via ** part-of
    ]
    component CStAll_PersonImGesundheitsberuf [
        **ISiK Person im Gesundheitsberuf**
        ====
    ]
}
'CSt_MedInfo --> CStAll_MedikationsListe
folder CSt_MedVerab as "Systeme mit dem Charakter der \n Medikationsverabreichung" {
    component _MedVerab [
    **ISiK MedikationsVerabreichung**
    ====
    Suche anhand von
    * ** :** medication
    * ** :** patient
    * ** :** context
    * ** :** performer
    ]
    component "ISiK Medikament "
    component "ISiK Patient "
    component "ISiK Kontakt Gesundheitseinrichtung "
    component "ISiK Person im Gesundheitsberuf "
}

folder CSt_MedVerord as "Systeme mit dem Charakter der \n Medikationsverordnung" {
    component _MedVerord [
    **ISiK MedikationsVerordnung**
    ====
    Suche anhand von
    * ** :** medication
    * ** :** patient
    * ** :** encounter
    * ** :** requester
    ]
    component "ISiK Medikament  "
    component "ISiK Patient  "
    component "ISiK Kontakt Gesundheitseinrichtung  "
    component "ISiK Person im Gesundheitsberuf  "
}

@enduml