'@startuml usecases
'usecase Medikation as "
'    = Medikation
'    
'    ___
'    Some text
'    === Neu-Verordnung
'    Other text
'    === Anpassung
'    Information
'    === Abgabe
'"
'@enduml

@startuml usecases
left to right direction
'skinparam packageStyle cloud
'skinparam linetype ortho

'actor :FHIR Repository: as DB << Application >>
actor :Heilberufler:
actor :Versicherter:
storage adverseUC as "Adverse Use Case" {
    storage (Verwechslung){
        (Dauer)
        (Termin)
        (Benötigte Expertise)
        (Patient)
    }
    (Mehrfachbelegung)
    (Terminüberhang)
    (Nicht-Erscheinen)
    (Personalüberhang)
}

storage gnrlUC as "Allgemein" {
    (Information)
    (Benachrichtigung)
    (Terminbuchung)
    (Sprechzeiten)
    (Schließzeiten)
    (Terminhistorie)
    (Personalplanung)
    storage booKUC as "Buchung von Terminen"{
        (Absage) 
        (Verschieben)
        (Durchführung)
        (Anfrage-Ablehnung)
        (Anfrage-Abbruch)
        (Anfrage-Reservierung)
    }
}

Heilberufler --> gnrlUC
Versicherter --> Information

'fncts --> adverseUC : mitigates
'fncts --> gnrlUC : enables
@enduml