name: Use Basis link check Stufe 5

on: 
  workflow_dispatch:
jobs:
  call-tool-link-check:
    uses: gematik/spec-isik-basismodul/.github/workflows/link-check.yml@main-stufe-5
    secrets:
      SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
      SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
      WORKFLOW_PERMISSION_GITHUB: ${{ secrets.WORKFLOW_PERMISSION_GITHUB }}